### ISSUE TITLE
Чел, ты мега классный

### ISSUE THREAD

**Issue by ghost** [SantaSpeen/anixart-abandoned#1]
Гений, но эндпоинты не все(ставь лаек, если юзаешь апи аников в тихую)

**Comment by SantaSpeen** [comment]
Что же на пункт "все", пока что не претендую, что что буду рад если поделишься тем, что тебе известно
`*Не ставит лайк*`, я не скрываю, что я описываю апи
А ещё, в реадми указан вк, можешь туда написать, если стеняешься

**Comment by ghost** [comment]
кста, в офицальный чат аника в телеге твой шедевр скинули(я там правда в бане, но ладно)

**Comment by ghost** [comment]
По поводу endpoints обратись к aniu.ru)
